---
title: "plot_theta.Rmd"
author: "Andrea Estandia"
date: "17/10/2022"
output:
  pdf_document: default
  html_document:
    df_print: paged
editor_options:
  chunk_output_type: console
params:
  beagle: chr30_1054214-chr30_1110750.beagle
---
  
```{r setup, echo=FALSE}
# Knitr settings: 
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
knitr::opts_chunk$set(echo = TRUE, eval = FALSE)
options(scipen = 999)
```

```{r, echo=FALSE}
source("./src/0.0_island_rule_source.R")
```

```{r}
migrants <- read_table("/media/sjoh4959/My Passport/Andrea/projects/0.0_migrants/reports/theta/migrants.thetasWindow.gz.pestPG")

residents <- read_table("/media/sjoh4959/My Passport/Andrea/projects/0.0_migrants/reports/theta/residents.thetasWindow.gz.pestPG")
```

Migrants
```{r}
order_chr <- as.character(seq(from = 5, to = 30))
reference = c(c("1", "1A", "2", "3", "4", "4A"), order_chr, "Z")
ref = factor(as.factor(paste0("chr", reference)), levels = c(c("chr1", "chr1A", "chr2", "chr3", "chr4", "chr4A"), paste0("chr",order_chr), "chrZ"))
migrants <- migrants[order(factor(as.factor(migrants$Chr), levels = ref)),]
migrants$n <- 1:nrow(migrants)

axismigrants <-
  migrants %>%
  group_by(Chr) %>%
  summarize(center = (max(n) + min(n)) / 2)

plot_migrants<- 
  migrants %>%
  ggplot(aes(x = n, y = Tajima, col=Chr)) + 
  scale_x_continuous(
    label = axismigrants$Chr,
    breaks = axismigrants$center,
    expand = c(0.01, 0.01)
  ) +
  geom_point()+
  scale_color_manual(values=rep(c("#348544", "#69bf5a"), length(unique(migrants$Chr))))+
  labs(x = "\n", y="Tajima's D", title = "Tasmanian migrants") +
  theme_classic() +
  theme(
    text = element_text(size=12, family="ubuntu"),
    legend.position = "none", 
    panel.border = element_blank())

plot_migrants_tW<- 
  migrants %>%
  ggplot(aes(x = n, y = tW, col=Chr)) + 
  scale_x_continuous(
    label = axisresidents$Chr,
    breaks = axisresidents$center,
    expand = c(0.01, 0.01)
  ) +
  geom_point()+
  scale_color_manual(values=rep(c("#356996", "#2f404f"), length(unique(residents$Chr))))+
  labs(x = "\n", y="Watterson Theta", title = "Tasmanian migrants") +
  theme_classic() +
  theme(
    text = element_text(size=12, family="ubuntu"),
    legend.position = "none", 
    panel.border = element_blank())
```

Residents
```{r}
order_chr <- as.character(seq(from = 5, to = 30))
reference = c(c("1", "1A", "2", "3", "4", "4A"), order_chr, "Z")
ref = factor(as.factor(paste0("chr", reference)), levels = c(c("chr1", "chr1A", "chr2", "chr3", "chr4", "chr4A"), paste0("chr",order_chr), "chrZ"))
residents <- residents[order(factor(as.factor(residents$Chr), levels = ref)),]
residents$n <- 1:nrow(residents)

axisresidents <-
  residents %>%
  group_by(Chr) %>%
  summarize(center = (max(n) + min(n)) / 2)

plot_residents<- 
  residents %>%
  ggplot(aes(x = n, y = Tajima, col=Chr)) + 
  scale_x_continuous(
    label = axisresidents$Chr,
    breaks = axisresidents$center,
    expand = c(0.01, 0.01)
  ) +
  geom_point()+
  scale_color_manual(values=rep(c("#356996", "#2f404f"), length(unique(residents$Chr))))+
  labs(x = "\n", y="Tajima's D", title = "Tasmanian residents") +
  theme_classic() +
  theme(
    text = element_text(size=12, family="ubuntu"),
    legend.position = "none", 
    panel.border = element_blank())

plot_residents_tW<- 
  residents %>%
  ggplot(aes(x = n, y = tW, col=Chr)) + 
  scale_x_continuous(
    label = axisresidents$Chr,
    breaks = axisresidents$center,
    expand = c(0.01, 0.01)
  ) +
  geom_point()+
  scale_color_manual(values=rep(c("#356996", "#2f404f"), length(unique(residents$Chr))))+
  labs(x = "\n", y="Watterson Theta", title = "Tasmanian residents") +
  theme_classic() +
  theme(
    text = element_text(size=12, family="ubuntu"),
    legend.position = "none", 
    panel.border = element_blank())
```

```{r}
(plot_migrants/plot_migrants_tW)
```

